# Generated by Django 3.2.12 on 2022-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
